version: '2137'

services:
  backend:
    build: ./backend
    ports:
      - "8000:80"
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.0
    ports:
      - "9200:9200"
    environment:
      - discovery.type=single-node

  kibana:
    image: docker.elastic.co/kibana/kibana:7.10.0
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200